services:

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=order
    volumes:
      - ./bin/sql/init.sql:/docker-entrypoint-initdb.d/init.sql